### ISSUE TITLE
Тестирование прототипа

### ISSUE THREAD

**Issue by MyDanielM** [DenisSavelev/-#10]
Скачать apk по ссылке: https://yadi.sk/d/f02PIgb_M1SUhQ
Тестируем, при нахождении багов - ссылку на отчёт в коммент к этой задаче.

**Comment by w1sk4zz** [comment]
Отчёт: https://docs.google.com/document/d/1cfQOMJArb68Qupfk5Vk4tW0060fRRxOX62q3EYKsMGQ/edit?usp=sharing

**Comment by w1sk4zz** [comment]
Отчёт по интерфейсу: https://docs.google.com/document/d/1byq6SA_X_kgZtJ79fs4cC3xjLfzGQrpLsJH2yIBdHFo/edit?usp=sharing
