### ISSUE TITLE
Спецификация на мобильное приложение

### ISSUE THREAD

**Issue by MyDanielM** [DenisSavelev/-#6]
Написать спецификацию (описание, мини ТЗ) на приложение "гид в твоём кармане" , включить пункты:
* Цели приложения
* Задачи приложения
* Функционал приложения (продумать архитектуру приложения)
Опционально:
* Логин скрин
* Модели поведения
Отчёт - гугл документ.

**Comment by AminaKlykova** [comment]
https://docs.google.com/document/d/1r_lWPSnphapjL3mqCD1sV-NM8fV26Ece_4A8zKfE5OA/edit?usp=sharing
