### ISSUE TITLE
Спецификация на 3д модели

### ISSUE THREAD

**Issue by MyDanielM** [DenisSavelev/-#7]
Написать спецификацию (описание, мини ТЗ) на 3д модели, включить пункты:
* Описание объектов для моделирования
* Указать степень проработки моделей
Опционально:
* Текстуры
Отчёт - гугл документ.

**Comment by nakulbet** [comment]
https://docs.google.com/document/d/1arD19h_xBT-Vc4r4A_K3pduvArcWsrDH-36IwVs3L-Q/edit
