### ISSUE TITLE
Подготовить вопросы к заказчику

### ISSUE THREAD

**Issue by MyDanielM** [DenisSavelev/-#9]
Переходим по ссылке, каждый пишет свой вопрос к заказчику:
https://docs.google.com/document/d/1TXT2VrMM5pgGawupUU-cHYpMvaxSKfjrwPcWCG_4hoY/edit
Как написать вопрос:
выбери номер из списка, добавь комментарий
ВНИМАНИЕ! Каждый человек берёт свой номер, один номер на человека
![Безымянный](https://user-images.githubusercontent.com/58218182/76971233-f9050a00-693d-11ea-8b92-ea9dc0889983.png)

**Comment by w1sk4zz** [comment]
2. Какой дизайн вы хотите видеть?  На что вы рассчитываете, то есть как видите конечный результат?
